pinecone:
  index_name: "agent-memory"
  dimension: 1536
  metric: "cosine"
  
openai:
  model: "text-embedding-ada-002"
  max_tokens: 8191

# Environment variables required:
# PINECONE_API_KEY - Your Pinecone API key
# PINECONE_ENVIRONMENT - Your Pinecone environment 
# OPENAI_API_KEY - Your OpenAI API key