name: Go Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: useblacksmith/setup-go@v6
      with:
        go-version: '1.24'

    - name: Generate Error Codes
      run: go generate ./...

    - name: Build
      run: go build -v .

    - name: Go Vulnerability Scan
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...

    - name: Test
      run: go test -v ./...

  test-install:
    name: Test Install Script
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [blacksmith-4vcpu-ubuntu-2204]
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Install Script (Linux)
      if: matrix.os == 'blacksmith-4vcpu-ubuntu-2204'
      run: |
        chmod +x ./install.sh
        # Test with default options (latest version)
        ./install.sh -d /tmp/agentuity-test
        # Verify installation
        /tmp/agentuity-test/agentuity --version
        
        # Test with specific version if available - simplified to avoid potential issues
        LATEST_VERSION=$(/tmp/agentuity-test/agentuity --version)
        if [ -n "$LATEST_VERSION" ]; then
          echo "Testing installation with specific version: $LATEST_VERSION"
          ./install.sh -d /tmp/agentuity-test-version -v $LATEST_VERSION
          # Verify installation with specific version
          INSTALLED_VERSION=$(/tmp/agentuity-test-version/agentuity --version)
          echo "Installed version: $INSTALLED_VERSION"
          echo "Expected version: $LATEST_VERSION"
          if [ "$INSTALLED_VERSION" = "$LATEST_VERSION" ]; then
            echo "Version verification successful"
          else
            echo "Version verification failed"
            exit 1
          fi
        fi
      shell: bash                                                                                                                                                                                        