name: Go Build and Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [blacksmith-4vcpu-ubuntu-2204, blacksmith-4vcpu-ubuntu-2204-arm, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: useblacksmith/setup-go@v6
      with:
        go-version: '1.24'

    - name: Generate Error Codes
      run: go generate ./...

    - name: Build
      run: go build -v .

    - name: Go Vulnerability Scan
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...

    - name: Test
      run: go test -v ./...

  test-install:
    name: Test Install Script
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [blacksmith-4vcpu-ubuntu-2204, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v4
    
    - name: Test Install Script (Linux)
      if: matrix.os == 'blacksmith-4vcpu-ubuntu-2204'
      run: |
        chmod +x ./install_test/docker-test-install.sh
        ./install_test/docker-test-install.sh
      shell: sh
      
    - name: Test Install Script (Linux ARM)
      if: matrix.os == 'blacksmith-4vcpu-ubuntu-2204-arm' 
      run: |
        chmod +x ./install_test/docker-test-install.sh
        ./install_test/docker-test-install.sh
      shell: sh
      
    - name: Test Install Script (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        chmod +x ./install.sh
        # Test with default options (latest version) - use --no-brew to skip Homebrew
        ./install.sh -d /tmp/agentuity-test --no-brew
        # Verify installation
        /tmp/agentuity-test/agentuity --version
        
        # Test installing over existing installation to verify segfault fix
        echo "Testing installation over existing binary to verify segfault fix..."
        ./install.sh -d /tmp/agentuity-test --no-brew
        # Verify installation still works after reinstall
        /tmp/agentuity-test/agentuity --version
        
        echo "macOS double installation test passed - segfault fix verified"
      shell: bash
      
